### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by kamil7732** [vdvm/nginx-watermark#3]
I build 1.9.15 with this module
yes with --with-http_image_filter_module

sadly I can't make it run
invalid parameter "watermark" in

my config file has a line like this
image_filter watermark "/var/www/logo2.png" "bottom-right";
also I've tried without quotation marks

**Comment by TrurlMcByte** [comment]
This is patch for existing http_image_filter_module

```
cd ..../nginx-$NGINX_VERSION && patch -p0 < ...../nginx-watermark/nginx-watermark.patch 
```

(last tested with version 1.10.2)

**Comment by kamil7732** [comment]
Works as you stated. Another question is how you would do a variable?

image_filter watermark /etc/nginx/html/$watermarkUrl center; doesn't work
any combination with variable has problems :(

**Comment by TrurlMcByte** [comment]
Try branch "vars" https://github.com/vdvm/nginx-watermark/tree/vars

**Comment by kamil7732** [comment]
Works like a charm. Thank you!
