### ISSUE TITLE
Watermark with Resize

### ISSUE THREAD

**Issue by handelcamilo** [vdvm/nginx-watermark#4]
Hi, is there a way to add a watermark and resize the image at the same time?
When "image_filter watermark" stands below "image_filter resize", the image cant resize.
When "image_filter resize" stands below "image_filter watermarks", the image dont show the watermark.

Code:
`alias /home/ubuntu/SERVER/uploads/$image;
            image_filter_interlace on;
            image_filter resize $width -;
            image_filter_jpeg_quality 75;
            image_filter_buffer 12M;
            image_filter watermark /path/logo.png center;`

Thank you!
ps: Sorry for bad english.

**Comment by TrurlMcByte** [comment]
Just do it in two locations with rewrite

**Comment by handelcamilo** [comment]
Please @TrurlMcByte , could you give me an example?
For now, I have two pieces of code where the image is manipulated.

location ~ "^/media/(?<width>\d+)-w/(?<image>.+)$" {
        # Proxy to internal image resizing server.
        proxy_pass http://localhost:8888/media/$width-w/$image;
        proxy_cache images;
        proxy_cache_valid 200 30d;
        proxy_http_version 1.1;
    }

server {
        server_name localhost;
        listen 8888;

        location ~ "^/media/(?<width>\d+)-w/(?<image>.+)$" {
            alias /home/ubuntu/git/app-gp/CODIGO/SERVER/uploads/$image;
            image_filter resize $width -;
            image_filter_jpeg_quality 75;
            image_filter_buffer 12M;
        }
}

I dont know where I could add the watermark on the resized image :(

Thank you so much!

**Comment by TrurlMcByte** [comment]
Use proxy_pass to server itself (or nginx cluster)
For each filter separate location and, if need, proxy_pass to other location to combine filters.
It's nginx image_filter limitation.
